# Generated by Django 3.0.3 on 2020-02-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=252)),
                ('description', models.CharField(blank=True, max_length=252)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProvidedByTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_management.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrolledToCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_enroled_form', models.DateField()),
                ('enrolled_till', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True)),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_management.CourseProvidedByTeacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
