# Generated by Django 3.0.3 on 2020-02-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
