# Generated by Django 3.0.3 on 2020-02-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0002_auto_20200207_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
    ]
