# Generated by Django 3.0.3 on 2020-02-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0004_auto_20200207_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprovidedbyteacher',
            old_name='id',
            new_name='course_teacher_id',
        ),
        migrations.RenameField(
            model_name='studentenrolledtocourse',
            old_name='id',
            new_name='enrollment_id',
        ),
    ]
