# Generated by Django 3.0.3 on 2020-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0005_auto_20200207_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolledtocourse',
            name='enrolled_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
